### ISSUE TITLE
Feature request: Attachments

### ISSUE THREAD

**Issue by emiloberg** [EddyVerbruggen/nativescript-email#1]
Being able to attach files (e.g. images) would be awesome!

**Comment by pablomaurer** [comment]
+1

**Comment by karlix** [comment]
+1

**Comment by EddyVerbruggen** [comment]
The master repo has work-in-progress support for attachments. See [the example in the readme](https://github.com/EddyVerbruggen/nativescript-email#compose).

**Comment by EddyVerbruggen** [comment]
Full support landed in 1.3.0
