### ISSUE TITLE
The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value

### ISSUE THREAD

**Issue by dotdreaming** [EddyVerbruggen/nativescript-email#10]
I have just tried uploading a build to the Apple app store and I received an email from AppStore Team saying it rejected my app due to new privacy-sensitive data usage policy. See the email contents below:
"
_Dear developer,

We have discovered one or more issues with your recent delivery for "App Name". To process your delivery, the following issues must be corrected:

This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team_
"

The only part of my app that could relate to NSCalendarUsageDescription is your email plugin. Do you think this is correct?

If so, do you know what I need to put in the app info.plist in order to successfully submit the app again?

many thanks

**Comment by EddyVerbruggen** [comment]
Are you 100% positive you've reported this issue in the right GitHub repo? This plugin does nothing with the Calendar.

**Comment by dotdreaming** [comment]
No, I'm not 100%. That's why I was enquiring with you to see if this was correct. 
In my app is very simple- your plugin is the only thing that is relevantly close to nscalendar. I thought that the email and calendar api's could be linked. 
I didn't know if you have come across this issue when publishing a iOS app to the App Store with the new privacy rules

**Comment by EddyVerbruggen** [comment]
I've had to add the description to my nativescript-calendar plugin but not this one. Maybe you've had that installed before and there's a file lingering.

**Comment by davorpeic** [comment]
Just an update to all that bump to this issue as I did, it is not related with this plugin, but if you use nativescript-ui, even if you dont use Calendar component, NS is still making the call, so you need to add that key that will be prompt only in case calendar is called, in my case I'm never calling it..
More about: http://www.telerik.com/forums/2016-3-914-3-nscalendarsusagedescription-nsphotolibraryusagedescription-required-when-deploying-to-testflight

I added this key into my Info.plist
```
<key>NSCalendarsUsageDescription</key>
<string>This app need to access your calendar events</string>
```

**Comment by EddyVerbruggen** [comment]
You're right, that bit me too!

**Comment by davorpeic** [comment]
Yeah, I see that NS will eventually split all components as separated plugins so that should fix this ugly workaround :)
