### ISSUE TITLE
Composing an email with attachments and file-not-found.

### ISSUE THREAD

**Issue by erjdriver** [EddyVerbruggen/nativescript-email#13]
If I send an email with an attachment with invalid filename - that rightly prints the file-not-found message but doesn't reject the promise. Continues on to selection of e-mail client...shouldn't this be an error message.

Not a big deal but I have a uri to a file (from image-picker) that looks like the following, maybe this format could be parsed.

content://com.android.providers.media.documents/document/image%3A742

Thanks.

**Comment by erjdriver** [comment]
Doing some googling, I found that the following will convert the content uri to a physical path.

`Cursor cursor = this.getContentResolver().query(_uri, new String[] { android.provider.MediaStore.Images.ImageColumns.DATA }, null, null, null);
    cursor.moveToFirst();   
    filePath = cursor.getString(0);

`

**Comment by EddyVerbruggen** [comment]
I guess it would make sense to reject the promise in this case.
