### ISSUE TITLE
iOS - module returns false for available() even though email clients/accounts are enabled.

### ISSUE THREAD

**Issue by erjdriver** [EddyVerbruggen/nativescript-email#14]
I've got:

`   emailModule.available().then( function( bAvailable: boolean )
    {
        console.log( "email available=" + bAvailable );
    } );
`

Returns false on an iOS device - even though email clients and accounts are enabled - specifically GMail.

I don't think the build-in iOS email client has an account attached.

Is that a problem?

**Comment by EddyVerbruggen** [comment]
Are you able to use the Gmail app nonetheless?

**Comment by erjdriver** [comment]
Normally if I try to share a photo on that phone - a list of all the shareable apps open up - including messenger and gmail is one of them. I select it and that's used.

In this case available is returning false.

Not sure what the plug-in is looking for - a default email client or an app email client account.

Pretty sure the apple email client is not set up - i.e. doesn't have an account associated with it.

**Comment by EddyVerbruggen** [comment]
I understand `available` returns false, but if you ignore that and just try and componse the email anyway, what happens? I don't have the Gmail app on my phone, that's why I ask.

**Comment by erjdriver** [comment]
Ok I did that and getting a dialog popup from within the plugin

NO MAIL ACCOUNTS
Please set up a Mail account in order to send email.

Looking your your email.ios.ts source code - not quite sure who's generating that above dialog.
It seems to be the system itself.

Event though at the beginning of your compose() you have

`if (!that.available()) {
        reject("No mail available");
      }
`
So not quite sure why that's not being rejected - even though I don't think i'm handling the rejection properly.


Again this issue is on ios - there's definitely an email client set up (gmail)

On Android it works - haven't tested with NO mail clients.



`       emailModule.available().then( function( bAvailable: boolean )
        {
            console.log( "email available=" + bAvailable );

            //if ( bAvailable )
            {
                let subject_line : string = "subject";

                emailModule.compose(
                {
                    subject: subject_line,
                    //body: "Hello <strong>dude</strong> :)",
                    to: ['test@gmail.com'],
                    appPickerTitle: 'Compose with..' // for Android, default: 'Open with..'
                }).then(function()
                {
                    console.log("Email composer closed");
                });
            }
        } );
`

**Comment by lukeramsden** [comment]
@erjdriver Did you manage to fix the issue?

**Comment by erjdriver** [comment]
No I didn't.

Under ios - I disregard bAvailable.

` if ( platformModule.isIOS || bAvailable )`

**Comment by mspusta78** [comment]
Updated to NS 5 and running the following on iOS doesn't work
I keep getting: Error: No mail available

I can send email using GMAIL client and GMAIL is setup

var email = require("nativescript-email");

    email.compose({
        subject: "Yo",
        body: "Hello <strong>dude</strong> :)",
        to: ['eddyverbruggen@gmail.com'],
        appPickerTitle: 'Compose with..' // for Android, default: 'Open with..'
    }).then(
    function() {
        console.log("Email composer closed");
    }, function(err) {
        console.log("Error: " + err);
    });

**Comment by EddyVerbruggen** [comment]
@mspusta78 I just tested on iPhone X with the standard mail app (that's what's checked by the plugin, not Gmail) and it all works similar to NativeScript 4 for me. Do you see a difference between 4 and 5? And is that with the default mailclient, or the Gmail app?

**Comment by mspusta78** [comment]
I was able to make it work with the standard mail app as well. So this is
not a NS 5 issue. It is Gmail client issue.

I was under the impression that Gmail client was detected as well,
(eventhough attachment was not supported).

Can we request that please? Can you support Gmail client without the
attachment support?

Thanks

Martin

**Comment by EddyVerbruggen** [comment]
Hey Martin,

This plugin is meant to open a draft in the stock mail app, I've never considered (nor tried) 3rd party clients.

Because of your request, I looked into what it would take to support Gmail, and found this: https://developers.google.com/gsuite/guides/ios - so an additional library is required which would make this plugin "heavier" than it currently is (atm there are no external dependencies). I'm not really fond of that as I'm pretty sure the next request will be "what about Outlook support?" and I'd have to add yet another 3rd party lib, etc, etc.

Maybe it's best to check for availability with this plugin, and if not supported use a 'social share' plugin that opens the share sheet so any available email client can be picked by the user.

**Comment by mspusta78** [comment]
Eddy,

Thanks for looking into this. I agree 100% with your finding and response.
I did exactly what you suggested. I check for availability and if not
supported I am using "social share" plugin.
Everything works like charm!

Thanks again for all your help and support to NS community.

Martin

**Comment by EddyVerbruggen** [comment]
Awesome! I'll add a hint to the readme, to help others.

**Comment by ineiti** [comment]
Very late to the party: I did a simple

```
openUrl("mailto:test@test.com")
```

And for just opening a new email, given the address, that works fine.
