### ISSUE TITLE
Callback after submitting email

### ISSUE THREAD

**Issue by adnanaliarshad** [EddyVerbruggen/nativescript-email#15]
Is there a way to execute a code after email is sent. Basically is there any callback for this functionality?

**Comment by EddyVerbruggen** [comment]
On iOS then `then` will contain a boolean indicating whether or not an email was sent, see [this plugin code](https://github.com/EddyVerbruggen/nativescript-email/blob/89fc6307e19bd724e5a2f989313a8eb001c1d2af/email.ios.js#L64).

On Android it's not possible, see [this plugin code](https://github.com/EddyVerbruggen/nativescript-email/blob/89fc6307e19bd724e5a2f989313a8eb001c1d2af/email.android.js#L85-L86).
