### ISSUE TITLE
Hint not showing on iOS?

### ISSUE THREAD

**Issue by lukeramsden** [EddyVerbruggen/nativescript-email#19]

**Comment by EddyVerbruggen** [comment]
What hint? Please be more elaborate. Also, is there a difference with Android?

**Comment by lukeramsden** [comment]
The `hint` property. Works fine on Android.

**Comment by EddyVerbruggen** [comment]
Please provide a link to the readme or code mentioning the `hint` property. [I can't find it in the repo](https://github.com/EddyVerbruggen/nativescript-email/search?utf8=%E2%9C%93&q=hint&type=).

**Comment by lukeramsden** [comment]
Wait a second, this was meant to be the nativescript-drop-down repo...

Sorry :/
