### ISSUE TITLE
Crashing on iOS (emulator)

### ISSUE THREAD

**Issue by emiloberg** [EddyVerbruggen/nativescript-email#2]
Crashes on a complete clean NativeScript 1.4 app.

Reproducible by:

```
tns create myapp
cd myapp
tns platform add ios
tns plugin add nativescript-email
# editing the main-page.js so that it looks like the snippet below.
# editing the main-page.xml so that it has a label with tap="tapAction"
tns emulate ios --device iPhone-6
```

On tap, screen looks like this for a second:
![skarmavbild 2015-10-23 kl 16 05 08](https://cloud.githubusercontent.com/assets/4673048/10694684/dba68322-799f-11e5-939b-7599bedac733.png)

Notice how only subject is filled out, not `to`, `body`, `cc` etc.

Then it crashes with this crash log: https://gist.github.com/emiloberg/c6ef9a1d69d3a9a964b8

```
var email = require("nativescript-email");

function pageLoaded(args) {
    var page = args.object;
}

function tapAction() {
  email.available().then(function(avail) {
      console.log("Email available? " + avail);

      email.compose({
          subject: "Yo",
          body: "Hello <strong>dude</strong> :)",
          to: ['eddyverbruggen@gmail.com', 'to@person2.com'],
          cc: ['ccperson@somewhere.com'],
          bcc: ['eddy@combidesk.com', 'eddy@x-services.nl']
      }).then(function(r) {
          console.log("Email composer closed");
      });

  })
}

exports.pageLoaded = pageLoaded;
exports.tapAction = tapAction;
```

**Comment by emiloberg** [comment]
However, doesn't crash on my real iPhone-5

**Comment by EddyVerbruggen** [comment]
Thanks for reporting this back in the day :)

A while ago I added a check for the iOS simulator (since it doesn't support emailing from an app); it gracefully rejects sending an email, instead of crashing.
