### ISSUE TITLE
AndroidRuntimeException

### ISSUE THREAD

**Issue by ivankaptue** [EddyVerbruggen/nativescript-email#23]
After update nativescript plugin to latest version,  my code don't work. I have this error.

JS: Error in email.compose: Error: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
 android.app.ContextImpl.startActivity(ContextImpl.java:1344)
JS:     android.app.ContextImpl.startActivity(ContextImpl.java:1331)
JS:     android.content.ContextWrapper.startActivity(ContextWrapper.java:322)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1043)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:925)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:912)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:896)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:888)
JS:     com.tns.gen.java.lang.Object_frnal_ts_helpers_l58_c38__MenuItemClickListenerImpl.onMenuItemClick(Object_frnal_ts_helpers_l58_c38__MenuItemClickListenerImpl.java:12)
JS:     android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:203)
JS:     android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:762)
JS:     android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:810)
JS:     android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
JS:     android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:957)
JS:     android.support.v7.view.menu.MenuPopup.onItemClick(MenuPopup.java:127)
JS:     android.widget.AdapterView.performItemClick(AdapterView.java:300)
JS:     android.widget.AbsListView.performItemClick(AbsListView.java:1186)
JS:     android.widget.AbsListView$PerformClick.run(AbsListView.java:3099)
JS:     android.widget.AbsListView$3.run(AbsListView.java:4046)
JS:     android.os.Handler.handleCallback(Handler.java:739)
JS:     android.os.Handler.dispatchMessage(Handler.java:95)
JS:     android.os.Looper.loop(Looper.java:135)
JS:     android.app.ActivityThread.main(ActivityThread.java:5354)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     java.lang.reflect.Method.invoke(Method.java:372)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)

**Comment by EddyVerbruggen** [comment]
Thanks, I was just ahead of you in #22
