### ISSUE TITLE
Not working with angular

### ISSUE THREAD

**Issue by vinayhfs** [EddyVerbruggen/nativescript-email#3]
Email plugin Not working in nativiescript + ng  but works in just nativescript 
Error - JS: Unhandled Promise rejection: Cannot read property 'startActivity' of undefined ; 
Zone: angular ; Task: Promise.then ; Value: TypeError: Cannot read property 'startActivity' of undefined
JS: Error: Uncaught (in promise): TypeError: Cannot read property 'startActivity' of undefined

**Comment by EddyVerbruggen** [comment]
Perhaps you're better served by moving this to StackOverflow of the NativeScript Slack channel since this doesn't ring a bell for me...

**Comment by vinayhfs** [comment]
Fixed - context.startActivity(mailIntent);  context was null even though set at top. 
So line changed to application.android.context.startActivity(mailIntent);

**Comment by EddyVerbruggen** [comment]
Ah, yeah, that's part of [this changeset](https://github.com/EddyVerbruggen/nativescript-email/commit/cb39ebdd3668ec55712580d80c314b14c36b9bc4) but it's not released yet, I'll do that now.
