### ISSUE TITLE
Module not found: Error: Can't resolve 'nativescript-email'

### ISSUE THREAD

**Issue by kuisza** [EddyVerbruggen/nativescript-email#32]
I made the necessary steps written on this site (`https://www.npmjs.com/package/nativescript-email`) to implement nativescript-email. 

I imported it:

import * as email from "nativescript-email";

And the in the code I wanted to test it:

    email.available((avail: boolean) => {
      console.log("Email available? " + avail);
    })

The code is in TypeScript, I work with angular. If I do 'npm start' it does no compile and get the following error message: 

ERROR in ./src/app/generate-doc/generate-doc.component.ts
Module not found: Error: Can't resolve 'nativescript-email'

**Comment by EddyVerbruggen** [comment]
Please check the demo in the repo, or share your own so I can take a look.
