### ISSUE TITLE
UIDevice.currentDevice is not a function (Xcode 8/iOS10)

### ISSUE THREAD

**Issue by raefa** [EddyVerbruggen/nativescript-email#8]
Hi @EddyVerbruggen. I think this is a similar issue to the local notifications plugin. On iOS10 (Xcode 8) I get this: `CONSOLE LOG file:///app/tns_modules/nativescript-email/email.js:10:18: Error in email.available: TypeError: UIDevice.currentDevice is not a function. (In 'UIDevice.currentDevice()', 'UIDevice.currentDevice' is an instance of UIDevice)`

**Comment by EddyVerbruggen** [comment]
Thanks @raefa! I also saw `UIApplication.sharedApplication` causing the same issue.

Can you please try from the GitHub master branch? Should fix it. It will take a few days before I'll be able to use iOS 10 SDK myself so I can't test it..

**Comment by EddyVerbruggen** [comment]
Installed Xcode 8 and found another issue. All fixed in plugin version 1.3.2.
